const router = require('express').Router();
const locationController = require('../controllers/locationController')
router.post('/newCountry',locationController.createCountry)
router.get('/listCountry',locationController.listCountry)
router.get('/getLocation',locationController.getCountryStateCity)
router.get('/viewCountry/:id',locationController.viewCountry)
router.get('/getState/:id',locationController.getState)
router.put('/updateCountry',locationController.updateCountry)
router.delete('/deleteCountry/:id',locationController.deleteCountry)
router.post('/updateStatus',locationController.updateStatus)
router.get('/countries/:page', locationController.listCountry)
router.post('/newState',locationController.createStates)
router.get('/listingStates',locationController.listingStates)
router.get('/viewState/:id',locationController.viewStates)
router.put('/updateState',locationController.updateStates)
router.delete('/deleteState/:id',locationController.deleteStates)
router.post('/changeStatus',locationController.changeStatus)
router.get('/States/:page', locationController.listStates)
router.post('/newCity',locationController.createCitys)
router.get('/listCity',locationController.listCitys)
router.get('/getCity/:id',locationController.getCity)
router.get('/listingcities',locationController.listingcities)
router.get('/viewCity/:id',locationController.viewCitys)
router.put('/updateCity',locationController.updateCitys)
router.delete('/deleteCity/:id',locationController.deleteCitys)
router.post('/status',locationController.Status)
router.get('/cities/:page', locationController.listCitys)
router.get('/listingCity', locationController.listingCity)
router.get('/activeCities', locationController.activeCities)
module.exports = router;
